import Head from 'next/head'
//import Image from 'next/image'
//import { Inter } from 'next/font/google'
import {db,doc, getDocs, collection} from '/pages/firebase'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const [events, setEvents] = useState([]);
  const router = useRouter()
  // useEffect(()=>{
  //   const docRef = collection(db, "events");
  //    const snapshots =  getDocs(docRef)
  //    const docs = snapshots.docs.map((doc) =>doc.data())
  //    console.log(snapshots);
  //    console.log(docs);
  //  },[])
  useEffect(() => {
    async function fetchEventsData() {
      const querySnapshot = await getDocs(collection(db, 'events'));
      const eventsData = querySnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }));
      setEvents(eventsData);
    }

    fetchEventsData();
  }, []);

  const handleJoin = (e) => {
    e.preventDefault();
    alert('Meeting details will be sent to provided Email.')
    //router.push('/joinevent');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <h2>Upcoming Event Details</h2>
        <div className={styles.cardcontainer}>
      {events.map((event) => ( 
        <div className={styles.card}>
        <div className={styles.cardbody} key={event.id}>
          <h2 className={styles.cardtitle}>{event.title}</h2>
          <p className={styles.carddiscription}>{`Topic: ${event.description}`}</p>
          <span className={styles.carddate}>{`Date: ${event.date}`}</span>
          <button onClick={handleJoin} className={styles.btnview}>Join</button>
        </div>
        </div>
      ))}
    </div>
      
    </>
  )
}
